### ISSUE TITLE
Invalid Memory Address

### ISSUE THREAD

**Issue by Oregon-Tech-Ninja** [ainsleyc/factual-go-driver#4]
I get the following error attempting to use your library. Any ideas?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x80495e2]

goroutine 1 [running]:
panic(0x8322480, 0x1870a038)
    /usr/local/go/src/runtime/panic.go:481 +0x326
main.main()
    /home/andrew/Desktop/go/src/scan/serve.go:54 +0x5e2

```

**Comment by ainsleyc** [comment]
Hi there,

Hmm not really. Do you have a longer stack trace for the error that indicates the library somewhere?

**Comment by Oregon-Tech-Ninja** [comment]
I'm not sure, but I'm also recieving api-key errors on every request I make
otherwise.

On Wed, Jul 13, 2016 at 8:47 AM, Ainsley Chong notifications@github.com
wrote:

> Hi there,
> 
> Hmm not really. Do you have a longer stack trace for the error that
> indicates the library somewhere?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ainsleyc/factual-go-driver/issues/4#issuecomment-232398049,
> or mute the thread
> https://github.com/notifications/unsubscribe/APmUR3aCa9KFgQiYKR9w1RdTrz7Ng1vTks5qVQibgaJpZM4JLFHQ
> .

## 

OregonTech.Ninja
Andrew LaFountain
